version: '2'

linters:
  default: all
  disable:
    - exhaustruct # is only intended for use in special cases.
    - recvcheck
  settings:
    depguard:
      # Only allow imports from the stdlib & this module
      rules:
        all:
          list-mode: strict
          files:
            - $all
          allow:
            - $gostd
            - github.com/percivalalb/sipuri
    varnamelen:
      max-distance: 17 # default of 5 makes the linter annoying to use.
  exclusions:
    generated: lax
    rules:
      # exclude some linters on test files.
      - linters:
          - funlen # some test functions can be long.
        path: _test\.go
      - linters:
          - golint
          - revive
        text: returns unexported type.*sipuri\.uriOption
      - linters:
          - ireturn
        path: sipuri\.go
    paths:
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
