run:
  timeout: 10m

linters:
  enable-all: true
  disable:
    - exhaustruct      # is only intended for use in special cases.
    - exhaustivestruct # deprecated and replaced by the above.
    - maligned         # deprecated and replaced by official fieldalignment.

issues:
  exclude-rules:
    # exclude some linters on test files.
    - path: _test\.go
      linters:
        - funlen # some test functions can be long.
