version: 2.1

orbs:
  golangci-lint: valimail/golangci-lint@0.2.0

jobs:
  test:
    parameters:
      version:
        description: "go version tag"
        default: "latest"
        type: string
    working_directory: ~/repo
    docker:
      - image: cimg/go:<<parameters.version>>
    resource_class: small # 1 vCPU, 2GB RAM 
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run tests
          command: |
            gotestsum --junitfile report.xml --format testname -- -coverprofile=coverage.txt -race -v
            go tool cover -html=coverage.txt -o coverage.html
      - store_test_results:
          path: report.xml
      - store_artifacts:
          path: coverage.html

workflows:
  test:
    jobs:
      - golangci-lint/lint:
          tag: 'v1.57.2'
      - test:
          matrix:
            parameters:
              version:
                - '1.22'
                - '1.21'
                - '1.20'
                - '1.19'
                - '1.18'
